
import * as XLSX from 'xlsx';
import path from 'path';

const TOTAL_STUDENTS = 478;

// Config
// We will split 478 into 4 roughly equal groups
const groups = [
    { code: 'MCA', batch: 24, count: 120, sem: 3 },
    { code: 'MCA', batch: 25, count: 120, sem: 1 },
    { code: 'MCAI', batch: 24, count: 119, sem: 3 },
    { code: 'MCAI', batch: 25, count: 119, sem: 1 },
];

const students: any[] = [];
let globalIndex = 1;

groups.forEach(g => {
    for (let i = 1; i <= g.count; i++) {
        // Format: SJC + Batch + Code + Number (4 digits, padded)
        // e.g. SJC24MCA2001
        const numStr = (2000 + i).toString();
        const regNo = `SJC${g.batch}${g.code}${numStr}`;

        students.push({
            'Register Number': regNo,
            'Name': `Student ${g.code} ${g.batch} - ${i}`,
            // 'Email': Removed as per user request (will be auto-generated by backend)
            'Program': g.code === 'MCAI' ? 'Integrated MCA' : 'MCA', // Helping the import a bit, or we could leave blank to test smart import
            'Semester': `S${g.sem}`, // S1 or S3
            // 'BatchYear' is inferred
        });
        globalIndex++;
    }
});

// Create Workbook
const wb = XLSX.utils.book_new();
const ws = XLSX.utils.json_to_sheet(students);
XLSX.utils.book_append_sheet(wb, ws, 'Students');

// Write to file
const outputPath = path.resolve('c:\\Users\\hp\\Desktop\\Seat-Sync\\dummy_students_no_email.xlsx');
XLSX.writeFile(wb, outputPath);

console.log(`Generated ${students.length} students to ${outputPath}`);
